# Generated by Django 6.0.6 on 2026-06-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_curso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("nome", models.CharField(max_length=200)),
                (
                    "cursos",
                    models.ManyToManyField(
                        blank=True, related_name="alunos", to="escola.curso"
                    ),
                ),
            ],
        ),
    ]
