# Generated by Django 6.0.6 on 2026-06-26 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Realizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("nacionalidade", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("sinopse", models.TextField()),
                ("duracao", models.IntegerField()),
                ("classificacao", models.FloatField()),
                ("poster", models.ImageField(blank=True, upload_to="filmes/")),
                (
                    "generos",
                    models.ManyToManyField(
                        blank=True, related_name="filmes", to="filmes.genero"
                    ),
                ),
                (
                    "realizador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filmes",
                        to="filmes.realizador",
                    ),
                ),
            ],
        ),
    ]
