# Generated by Django 6.0.6 on 2026-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genero",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="realizador",
            name="nacionalidade",
            field=models.CharField(max_length=200),
        ),
    ]
