# Generated by Django 6.0.6 on 2026-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("grau", models.CharField(max_length=50)),
                ("duracao_anos", models.IntegerField()),
                ("url_oficial", models.URLField()),
                ("descricao", models.TextField()),
            ],
        ),
    ]
