# Generated by Django 6.0.6 on 2026-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("ferramenta", "Ferramenta"),
                            ("base_dados", "Base de Dados"),
                        ],
                        max_length=50,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("url_oficial", models.URLField()),
                ("descricao", models.TextField()),
                ("nivel_interesse", models.IntegerField(default=3)),
            ],
        ),
    ]
