# Generated by Django 6.0.6 on 2026-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(max_length=200)),
                ("resumo", models.TextField()),
                ("ano", models.IntegerField()),
                ("classificacao", models.IntegerField()),
                ("url_documento", models.URLField(blank=True)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
    ]
