# Generated by Django 6.0.6 on 2026-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("certificado_url", models.URLField(blank=True)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
    ]
