# Generated by Django 6.0.6 on 2026-06-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entidade_relacionada", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField(blank=True)),
                ("erros_correcoes", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("foto_papel", models.ImageField(blank=True, upload_to="makingof/")),
                ("data_registo", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
