# Generated by Django 6.0.6 on 2026-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_makingof"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("tipo", models.CharField(max_length=100)),
                ("url_evidencia", models.URLField(blank=True)),
            ],
        ),
    ]
